#!/bin/sh

name=`basename "$0"`
tmp="$0"
tmp=`dirname "$tmp"`
tmp=`dirname "$tmp"`
bundle=`dirname "$tmp"`
bundle_contents="$bundle"/Contents
bundle_res="$bundle_contents"/Resources
bundle_lib="$bundle_res"/lib
bundle_bin="$bundle_res"/bin
bundle_data="$bundle_res"/share

export DYLD_LIBRARY_PATH="$bundle_lib"
export GSETTINGS_SCHEMA_DIR="$bundle_data/glib-2.0/schemas"

exec "$bundle_bin/nip4"

